### ISSUE TITLE
Race Condition 문제 

### ISSUE THREAD

**Issue by 1223v** [readyvery/readyBack#130]
- 현재 Spring 내에 synchronized 로 Spring 내부에서는 경쟁상태로부터 데이터의 무결성을 보장하긴 하지만 DB 테이블로 부터의 무결성을 보장하지는 않음 
- synchronized -> DB 테이블 락으로 변경해서 DB에서 데이터 무결성을 보장해야한다.

**Comment by marinesnow34** [comment]
#197 해결
