### ISSUE TITLE
카카오 전화 번호 없는 경우의 쿠폰 발급 이슈

### ISSUE THREAD

**Issue by 1223v** [readyvery/readyBack#153]
현재 카카오 전화 번호가 없어도 아이디가 생성되고 카카오 아이디를 만들때마다 새로운 쿠폰을 발급 받을 수 있음.

- 전화번호를 유니크로 판단하고 전화번호가 없는 계정은 자동으로 벤 처리 필요

**Comment by marinesnow34** [comment]
- 정책상 중복 전화번호 허용하기로 함
- 당분간은 쿠폰 발급 사용X -> 쿠폰을 직접 제공
